### ISSUE TITLE
Seems to choke on Postgis backend

### ISSUE THREAD

**Issue by OmenApps** [ariga/djangoviz#13]
My app uses postgis, and I received the following error when running `python manage.py djangoviz`:

```shell
Traceback (most recent call last):
  File "/app/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/djangoviz/management/commands/djangoviz.py", line 115, in handle
    db_driver = _get_db_driver()
  File "/usr/local/lib/python3.10/site-packages/djangoviz/management/commands/djangoviz.py", line 46, in _get_db_driver
    raise ValueError(f"Error reading database driver: {engine}")
ValueError: Error reading database driver: django.contrib.gis.db.backends.postgis
```

It seems [djangoviz.py](https://github.com/ariga/djangoviz/blob/d1695b55fc6d5c559fd0a6daec7e60b0b7629a73/djangoviz/management/commands/djangoviz.py#L36) only allows "MYSQL", "POSTGRESQL", or "SQLITE" as engines.

**Comment by rotemtam** [comment]
Hi @OmenApps 

Thanks for trying DjangoViz!


Correct, PostGIS is currently not supported by the Atlas Cloud Playground, which is used by djangoviz to create visualizations. Support for this will be added in the near future

HTH
